#!/bin/bash

# this didnt work in docker, ran it on a new separate machine because of NET_ADMIN (not the correct setting) error

sed -i 's/192.168.56.2/192.168.1.1/g' docker-pxe/Dockerfile
docker build -f ./docker-pxe/Dockerfile -t btardio-docker-pxe ./docker-pxe
docker run -it --net=host --rm btardio-docker-pxe
